version: '3.3'

services:
  drupal:
    container_name: drupal
    image: drupal:10-php8.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - ./sites:/var/www/html/sites
      - ./php:/usr/local/etc/php
    restart: unless-stopped

  drupal_database:
    container_name: drupal_database
    image: mariadb:latest
    env_file: .env
    volumes:
        - ./database:/var/lib/mysql
    restart: unless-stopped
