version: '3.3'

services:
  drupal:
    container_name: drupal
    image: drupal:10-php8.1
    ports:
      - 80:80
    volumes:
      - ./vol/drupal_modules:/var/www/html/modules
      - ./vol/drupal_profiles:/var/www/html/profiles
      - ./vol/drupal_themes:/var/www/html/themes
      - ./vol/drupal_sites:/var/www/html/sites
    restart: unless-stopped

  drupal_database:
    container_name: drupal_database
    image: mariadb:latest
    env_file: .env
    volumes:
        - ./vol/database:/var/lib/postgresql/data
    restart: unless-stopped
