version: '3.3'

services:
  drupal:
    container_name: drupal
    image: drupal:10-php8.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    restart: unless-stopped

  drupal_database:
    container_name: drupal_database
    image: mariadb:latest
    env_file: .env
    volumes:
        - ./database:/var/lib/mysql
    restart: unless-stopped
