version: '3.3'

services:
  drupal:
    container_name: drupal
    build:
      context: .
      dockerfile: docker/drupal/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
#      - ./var/www/html:/var/www/html
    restart: unless-stopped

  drupal_database:
    container_name: drupal_database
    image: mariadb:latest
    env_file: .env
    volumes:
        - ./var/lib/mysql:/var/lib/mysql
    restart: unless-stopped
