version: '3.3'

networks:
   vmangos-network:
     external: true

services:
  wordpress:
    container_name: wordpress
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.wordpress.entrypoints=web"
#     - "traefik.http.routers.wordpress.entrypoints=websecure"
     - "traefik.http.routers.wordpress.rule=Host(`${WEBSITE_URL}`,`${WEBSITE_URL_WWW}`)"
#     - "traefik.http.routers.wordpress.tls=true"
#     - "traefik.http.routers.wordpress.tls.certresolver=production"
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile 
    volumes:
      - ./var/www/html:/var/www/html
    networks:
     - vmangos-network
    restart: unless-stopped

  wordpress_database:
    container_name: wordpress_database
    image: mariadb:latest
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    env_file: .env
    networks:
     - vmangos-network
    restart: unless-stopped

  traefik:
    image: traefik:v2.10.4
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    # -- (Optional) Enable Dashboard, don't do in production
    #  - 8080:8080
    volumes:
      - ./etc/traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # -- (Optional) When using Cloudflare as Cert Resolver
    # environment:
    #   - CF_DNS_API_TOKEN=your-cloudflare-api-token
    # -- (Optional) When using a custom network
    networks:
      - vmangos-network
    restart: unless-stopped


