version: "3.8"
services:
  wordpress_database:
    container_name: wordpress_database
    build:
      context: .
      dockerfile: docker/database/Dockerfile
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./vol/database:/var/lib/mysql
    networks:
      - wordpress-network
    deploy:
      resources:
        limits:
          memory: 2048m

  wordpress_phpmyadmin:
    container_name: wordpress_phpmyadmin
    build:
      context: .
      dockerfile: docker/phpmyadmin/Dockerfile
    depends_on:
      - database
    restart: unless-stopped
    ports:
      - 8081:80
    environment:
      PMA_HOST: wordpress_database
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - wordpress-network

  wordpress_lazycms:
    container_name: wordpress_lazycms
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
      depends_on:
        - database
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress_database:3306 # use the same name as database service
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./vol/content:/var/www/html/wp-content
    networks:
      - wordpress-network

networks:
  wordpress-network:
    driver: bridge
