version: '3.3'

services:
  drupal:
    container_name: drupal
    image: drupal:10-php8.1
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./vol/drupal_modules:/opt/drupal/web/modules
      - ./vol/drupal_profiles:/opt/drupal/web/profiles
      - ./vol/drupal_themes:/opt/drupal/web/themes
    restart: unless-stopped

  drupal_database:
    container_name: drupal_database
    image: mariadb:latest
    env_file: .env
    volumes:
        - ./vol/database:/var/lib/postgresql/data
    restart: unless-stopped
