version: '3.3'

services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./var/www/html:/var/www/html
    restart: unless-stopped

  wordpress_database:
    container_name: wordpress_database
    image: mariadb:latest
    env_file: .env
    volumes:
        - ./var/lib/mysql:/var/lib/mysql
    restart: unless-stopped
