version: '3.3'

services:
  wordpress:
    container_name: wordpress
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.web.entrypoints=web"
     - "traefik.http.routers.web.rule=Host(`vanillareforged.org`)"
    image: wordpress:latest
    networks:
     - vmangos-network
    restart: unless-stopped

  wordpress_database:
    container_name: wordpress_database
    image: mariadb:latest
    env_file: .env
    networks:
     - vmangos-network
    restart: unless-stopped
