version: '3.3'

services:
  wordpress:
    container_name: wordpress
    build:
      context: .
      dockerfile: docker/wordpress/Dockerfile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./var/www/html:/var/www/html
    restart: unless-stopped

  wordpress_database:
    container_name: wordpress_database
    image: mariadb:latest
    env_file: .env
    volumes:
        - ./var/lib/mysql:/var/lib/mysql
    restart: unless-stopped

  wordpress_certbot:
    depends_on:
      - wordpress
    image: certbot/certbot
    container_name: wordpress_certbot
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./var/www/html:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN} -d ${WWWDOMAIN}
