version: '3.3'

services:
  drupal:
    image: drupal:latest
    ports:
      - 80:80
    volumes:
      - ./vol/drupal_modules:/var/www/html/modules
      - ./vol/drupal_profiles:/var/www/html/profiles
      - ./vol/drupal_themes:/var/www/html/themes
      - ./vol/drupal_sites:/var/www/html/sites
    restart: always

  drupal_database:
    image: mariadb:latest
    env_file: .env
    volumes:
        - ./vol/database:/var/lib/postgresql/data
    restart: always

volumes:
  drupal_modules:
  drupal_profiles:
  drupal_themes:
  drupal_sites:
  database:
