version: '3.3'

networks:
   vmangos-network:
     external: true

services:
  wordpress:
    container_name: wordpress
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.wordpress.entrypoints=web, websecure"
     - "traefik.http.routers.wordpress.rule=Host(`${WEBSITE_URL}`)"
     - "traefik.http.routers.wordpress.tls=true"
     - "traefik.https.routers.wordpress.tls.certresolver=production"
    image: wordpress:latest
    networks:
     - vmangos-network
    restart: unless-stopped

  wordpress_database:
    container_name: wordpress_database
    image: mariadb:latest
    env_file: .env
    networks:
     - vmangos-network
    restart: unless-stopped
