version: '3.3'

networks:
   vmangos-network:
     external: true

services:
  wordpress:
    container_name: wordpress
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.wordpress.entrypoints=websecure"
     - "traefik.http.routers.wordpress.rule=Host(`${WEBSITE_URL}`)"
     - "traefik.http.routers.wordpress.middlewares=wordpress@file"
     - "traefik.http.routers.wordpress.tls=true"
     - "traefik.http.routers.wordpress.tls.certresolver=production"
     - "traefik.http.routers.wordpress.service=wordpress"
     - "traefik.http.routers.wordpress.loadbalancer.server.port=80"
     - "traefik.docker.network=vmangos-network"
    image: wordpress:latest
    networks:
     - vmangos-network
    restart: unless-stopped

  wordpress_database:
    container_name: wordpress_database
    image: mariadb:latest
    env_file: .env
    networks:
     - vmangos-network
    restart: unless-stopped
