version: '3.3'

networks:
   vmangos-network:
     external: true

services:
  wordpress:
    container_name: wordpress
    labels:
    - traefik.enable=true
    - traefik.http.routers.wordpress.rule=Host(`${WEBSITE_URL}`) || Host(`${WEBSITE_URL_WWW}`)
    - traefik.http.services.wordpress.loadbalancer.server.port=80
    - traefik.http.middlewares.wordpressredirect.redirectregex.regex=^https://www\.(.*)
    - traefik.http.middlewares.wordpressredirec.redirectregex.replacement=https://$${1}
    - traefik.http.routers.wordpress.middlewares=wordpressredirec
    - traefik.http.routers.wordpress.tls.certresolver=production
    image: wordpress:latest
    networks:
     - vmangos-network
    restart: unless-stopped

  wordpress_database:
    container_name: wordpress_database
    image: mariadb:latest
    env_file: .env
    networks:
     - vmangos-network
    restart: unless-stopped
